title: 灵动键 FlexKey 文档
description: Android 自动化与快捷触发工具使用文档
lang: zh-CN
url: https://flexkey-docs.64bit.us
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
